/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package doxy;

import global.DoxyApp;
import japa.parser.JavaParser;
import japa.parser.ast.Comment;
import japa.parser.ast.CompilationUnit;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Rendra
 */
public class FrmParseTranslate extends javax.swing.JInternalFrame {
    private String selectedFile;
    /**
     * Creates new form FrmParseTranslate
     */
    public FrmParseTranslate() throws Exception {
        initComponents();
        if (DoxyApp.bridge.getSelectedSrcFile()==null) {
            JOptionPane.showMessageDialog(null, "Please choose a file first", "Choose file", JOptionPane.WARNING_MESSAGE);
        } else {
            processFile();
        }
    }
    
    private void processFile() throws Exception {
        selectedFile = DoxyApp.bridge.getSelectedSrcFile();
        FileInputStream in = new FileInputStream(selectedFile);
        CompilationUnit cu;
        try {
            cu = JavaParser.parse(in);
        } finally {
            in.close();
        }
        List<Comment> newComments = new ArrayList<>();
        List<Comment> srcComments = new ArrayList<>();
        srcComments = cu.getComments();
        StringBuilder sbComments = new StringBuilder();
        for(Comment cm : srcComments){
            //cm.setContent(" Rendra ");
            //newComments.add(cm);
            sbComments.append(cm.toString());
        }
        //cu.setComments();
        TAOri.setText(cu.getComments().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SPOri = new javax.swing.JScrollPane();
        TAOri = new javax.swing.JTextArea();

        TAOri.setEditable(false);
        TAOri.setColumns(20);
        TAOri.setRows(5);
        SPOri.setViewportView(TAOri);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPOri, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPOri, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SPOri;
    private javax.swing.JTextArea TAOri;
    // End of variables declaration//GEN-END:variables
}
